#! /bin/sh -e
### BEGIN INIT INFO
# Provides:           snmpd snmptrapd
# Required-Start:     $network $remote_fs $syslog
# Required-Stop:      $network $remote_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  SNMP agents
# Description:        NET SNMP (Simple Network Management Protocol) Agents
### END INIT INFO
set -e

. /lib/lsb/init-functions

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

test -x /usr/sbin/snmpd || exit 0

# Defaults
export MIBDIRS=/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp

SNMPDOPTS='-LS4d -Lf /dev/null -u snmp -g snmp -I -smux -p /var/run/snmpd.pid'

RETVAL=0
prog="snmpd"

start() {
	log_daemon_msg "Starting network management services:"
		start-stop-daemon --quiet --start --oknodo --exec /usr/sbin/snmpd \
		-- $SNMPDOPTS
	log_daemon_msg " snmpd"
}

stop() {
	log_daemon_msg "Stopping network management services:"
	start-stop-daemon --quiet --stop --oknodo --exec /usr/sbin/snmpd
    log_daemon_msg " snmpd"
}

restart(){
	stop
	sleep 2
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload|force-reload)
	log_daemon_msg "Reloading network management services:"
	start-stop-daemon --quiet --stop --signal KILL \
	    --pidfile /var/run/snmpd.pid --exec /usr/sbin/snmpd
	sleep 2
	start-stop-daemon --quiet --start --oknodo --exec /usr/sbin/snmpd \
		-- $SNMPDOPTS
	log_daemon_msg " snmpd"
	;;
  status)
	status=0
	status_of_proc /usr/sbin/snmpd snmpd || status=$?
	exit $status
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=1
esac

exit $RETVAL
